stg.GA_SessionData schema enhancements
SkillsFundingAgency/das-data-management pull request #105
Opened 2020-10-23 10:37 UTC by sarmaevanidfe

2020-10-28 11:36 UTC, arvinthseran approved these changes

2020-10-28 15:46 UTC, uhimabindu approved these changes
Approved.

2020-11-02 13:50 UTC, arvinthseran approved these changes

2020-11-02 14:15 UTC, uhimabindu requested changes

2020-11-02 14:15 UTC, uhimabindu commented on azure/template.json
> +        },
Please can you check why Azure/template.json is appearing in the Pull as File Changed. This shouldn't appear as it's already in master.

2020-11-03 16:23 UTC, uhimabindu approved these changes
Approved

2020-11-05 14:37 UTC, merged