Asintel 1016 resilience layer views
SkillsFundingAgency/das-data-management pull request #112
Opened 2020-11-13 10:33 UTC by sarmaevanidfe

Resilience layer views 
[ASData_PL].[DAS_SpendControl_V2]
[ASData_PL].[DAS_SpendControlNonLevy_V2]
[ASData_PL].[DAS_TransactionLine_V2]
[Data_Pub].[DAS_Commitments_V2]
[Data_Pub].[DAS_Employer_Account_Transfers_V2]
[Data_Pub].[DAS_Employer_Accounts_V2]
[Data_Pub].[DAS_Employer_AccountTransactions_V2]
[Data_Pub].[DAS_Employer_Agreements_V2]
[Data_Pub].[DAS_Employer_LegalEntities_V2]
[Data_Pub].[DAS_Employer_PayeSchemes_V2]
[Data_Pub].[DAS_Employer_Transfer_Relationship_V2]
[Data_Pub].[DAS_LevyDeclarations_v2]
[Data_Pub].[DAS_Payments_V2]

2020-11-13 11:47 UTC, arvinthseran requested changes

2020-11-13 11:47 UTC, arvinthseran commented on src/SFA.DAS.DATA.MANAGEMENT/StoredProcedure/PopulateSourceDbMetadataForImport.sql
> +,('Commitments','Providers','dbo','[Ukprn], [Name], [Created], [Updated]','','','Comt_Providers',0)
I believe the columns [Ukprn], [Name], should be under Columns to Mask?

2020-11-16 12:18 UTC, arvinthseran approved these changes

2020-11-23 16:02 UTC, uhimabindu requested changes

2020-11-23 16:11 UTC, sarmaevanidfe commented on src/SFA.DAS.DATA.MANAGEMENT/Views/ASDataPL_DAS_SpendControl_V2.sql
> +				,COALESCE(Account.DasAccountName, 'NA')                                    AS DasAccountName
in the sub query both DASAccountName and LegalEntityName are updated as 'Redacted' for those two views

2020-11-23 16:12 UTC, uhimabindu commented on src/SFA.DAS.DATA.MANAGEMENT/Views/ASDataPL_DAS_SpendControl_V2.sql
> +				,COALESCE(Account.DasAccountName, 'NA')                                    AS DasAccountName
Thanks, That's all looking then.

2020-11-23 16:12 UTC, uhimabindu approved these changes
Approved

2020-11-23 16:16 UTC, merged