Added ROATP Ver 2 tables
SkillsFundingAgency/das-data-management pull request #178
Opened 2021-05-06 16:31 UTC by sarmaevanidfe

2021-05-11 09:26 UTC, sarmaevanidfe commented on src/SFA.DAS.DATA.MANAGEMENT/StoredProcedure/PopulateMetadataRolesAndPermissions.sql
> +('BetaUser','ASData_PL','RP_FinancialData','TABLE','SELECT',0,1),
Updated the scripts as per comments above

2021-05-14 13:34 UTC, sarmaevanidfe commented on src/SFA.DAS.DATA.MANAGEMENT/StoredProcedure/PopulateMetadataRolesAndPermissions.sql
> +('BetaUser','ASData_PL','RP_FinancialData','TABLE','SELECT',0,1),
Logic amended for CreatedBy columns

2021-05-14 14:55 UTC, uhimabindu requested changes

2021-05-14 14:55 UTC, uhimabindu commented on src/SFA.DAS.DATA.MANAGEMENT/StoredProcedure/PopulateSourceDbMetadataForImport.sql
> +		,'select [Id],[ApplicationId],[AppealId],[FileStorageReference],[Filename],[ContentType],[Size],STUFF([UserId],2,len([UserId])-2,REPLICATE(''''*'''',len([UserId])-2)) As [UserId],STUFF([UserName],2
Might be good to add the same Checks to see if it is guid for all User Id Columns. In this case UserId.

2021-05-14 14:55 UTC, uhimabindu commented on src/SFA.DAS.DATA.MANAGEMENT/StoredProcedure/PopulateSourceDbMetadataForImport.sql
> +		,'select [Id],[ApplicationId],[SequenceNumber],[SectionNumber],[PageId],STUFF([Assessor1UserId],2,len([Assessor1UserId])-2,REPLICATE(''''*'''',len([Assessor1UserId])-2)) As [Assessor1UserId],[Asses
Might be good to add the same Checks to see if it is guid for all User Id Columns. Assessor1UserId and Assessor2UserId

2021-05-14 14:55 UTC, uhimabindu commented on src/SFA.DAS.DATA.MANAGEMENT/StoredProcedure/PopulateSourceDbMetadataForImport.sql
> +		,'Select [Id],[ApplicationId],[SequenceNumber],[SectionNumber],[PageId],STUFF([ModeratorUserId],2,len([ModeratorUserId])-2,REPLICATE(''''*'''',len([ModeratorUserId])-2)) As [ModeratorUserId],STUFF(
Might be good to add the same Checks to see if it is guid for all User Id Columns. In this case ModeratorUserId

2021-05-14 14:55 UTC, uhimabindu commented on src/SFA.DAS.DATA.MANAGEMENT/StoredProcedure/PopulateSourceDbMetadataForImport.sql
> +		,'select [Id],[ApplicationId],[GatewayApproved],[ModerationApproved],[Status],[ApplicationDeterminedDate],[InternalComments],[ExternalComments],STUFF([UserId],2,len([UserId])-2,REPLICATE(''''*'''',
Might be good to add the same Checks to see if it is guid for all User Id Columns. In this case UserId.

2021-05-14 15:09 UTC, uhimabindu commented on src/SFA.DAS.DATA.MANAGEMENT/StoredProcedure/PopulateSourceDbMetadataForImport.sql
> +		,'select [Id],[ApplicationId],[GatewayApproved],[ModerationApproved],[Status],[ApplicationDeterminedDate],[InternalComments],[ExternalComments],STUFF([UserId],2,len([UserId])-2,REPLICATE(''''*'''',
Waiting for Prod Data to arrive to see how the User Id looks like with Live Data. Until then it's agreed to keep it masked to be safe. Will need revisiting once we have Live Data.

2021-05-14 15:09 UTC, uhimabindu commented on src/SFA.DAS.DATA.MANAGEMENT/StoredProcedure/PopulateSourceDbMetadataForImport.sql
> +		,'Select [Id],[ApplicationId],[SequenceNumber],[SectionNumber],[PageId],STUFF([ModeratorUserId],2,len([ModeratorUserId])-2,REPLICATE(''''*'''',len([ModeratorUserId])-2)) As [ModeratorUserId],STUFF(
Waiting for Prod Data to arrive to see how the User Id looks like with Live Data. Until then it's agreed to keep it masked to be safe. Will need revisiting once we have Live Data.

2021-05-14 15:10 UTC, uhimabindu commented on src/SFA.DAS.DATA.MANAGEMENT/StoredProcedure/PopulateSourceDbMetadataForImport.sql
> +		,'select [Id],[ApplicationId],[SequenceNumber],[SectionNumber],[PageId],STUFF([Assessor1UserId],2,len([Assessor1UserId])-2,REPLICATE(''''*'''',len([Assessor1UserId])-2)) As [Assessor1UserId],[Asses
Waiting for Prod Data to arrive to see how the User Id looks like with Live Data. Until then it's agreed to keep it masked to be safe. Will need revisiting once we have Live Data.

2021-05-14 15:10 UTC, uhimabindu commented on src/SFA.DAS.DATA.MANAGEMENT/StoredProcedure/PopulateSourceDbMetadataForImport.sql
> +		,'select [Id],[ApplicationId],[AppealId],[FileStorageReference],[Filename],[ContentType],[Size],STUFF([UserId],2,len([UserId])-2,REPLICATE(''''*'''',len([UserId])-2)) As [UserId],STUFF([UserName],2
Waiting for Prod Data to arrive to see how the User Id looks like with Live Data. Until then it's agreed to keep it masked to be safe. Will need revisiting once we have Live Data.

2021-05-14 15:10 UTC, uhimabindu approved these changes
Approved

2021-05-17 13:52 UTC, merged