Added DWH lookup tables for SSA and Geography locations
SkillsFundingAgency/das-data-management pull request #268
Opened 2021-12-02 17:47 UTC by sarmaevanidfe

2021-12-08 14:54 UTC, uhimabindu requested changes

2021-12-08 15:30 UTC, sarmaevanidfe commented on src/SFA.DAS.DATA.MANAGEMENT/StoredProcedure/PopulateMetadataRolesAndPermissions.sql
> +('DWHLkpUser','lkp','Pst_LocalAuthority','TABLE','ALTER',0,1)
Updated the required syntax to make it work

2021-12-09 14:52 UTC, arvinthseran approved these changes

2021-12-09 15:00 UTC, uhimabindu approved these changes

2021-12-09 15:01 UTC, merged