Adding TransferRequest table
SkillsFundingAgency/das-data-management pull request #271
Opened 2021-12-13 17:10 UTC by sarmaevanidfe

2021-12-15 09:47 UTC, arvinthseran approved these changes

2021-12-15 10:42 UTC, uhimabindu requested changes

2021-12-15 10:42 UTC, uhimabindu commented on src/SFA.DAS.DATA.MANAGEMENT/Tables/AsDataPL_Comt_TransferRequest.sql
> +	[TransferApprovalActionedByEmployerEmail]	[nvarchar](255)		NULL,
Is this column needed Sarma TransferApprovalActionedByEmployerEmail - Looks PII to me, If not used better to exclude.

2021-12-15 10:46 UTC, uhimabindu approved these changes

2021-12-15 10:46 UTC, uhimabindu commented on src/SFA.DAS.DATA.MANAGEMENT/Tables/AsDataPL_Comt_TransferRequest.sql
> +	[TransferApprovalActionedByEmployerEmail]	[nvarchar](255)		NULL,
Sarma confirmed that it's needed for Reporting

2021-12-21 09:40 UTC, arvinthseran approved these changes

2021-12-21 10:14 UTC, merged